server {
    listen 5173;
    server_name localhost;


    location /assets/ {
        root /usr/share/nginx/html;
        gzip_static on;
        expires max;
        add_header Cache-Control "public, no-transform";
    }


    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    keepalive_timeout 65;
    client_max_body_size 10M;
}