version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    restart: always
    networks:
      - daily-wins-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - daily-wins-network

networks:
  daily-wins-network:
    driver: bridge